#!/bin/bash
args=2
if [ $# -ne $args ]
 then
  echo Wrong number of arguments - Usage: finding [int octal permissions] [int days] 
else

  count=(0 0 0 0 0)
  while read -p 'Give the name of a directory [blank to exit] : ' dirname; do

    if [ -z "$dirname" ]; then break; fi

    command1="find ${dirname}/* -perm $1 -type f"
    count1=$( $command1 |wc -l)
    ((count[0]+=$count1))
    echo " "
    echo "1. Find all files in directory tree with octal permissions:$1 => [Total: $count1]"
    $command1
    echo " "

    command2="find ${dirname}/* -mtime -$2 -type f"
    count2=$( $command2 |wc -l)
    ((count[1]+=$count2))
    echo " "
    echo "2. Find all files in directory tree that have been modified in the last $2 days => [Total: $count2]"
    $command2
    echo " "

    command3="find ${dirname} -atime -$2 -type d"
    count3=$( $command3 |wc -l)
    ((count[2]+=$count3))
    echo " "
    echo "3. Find all directories in directory tree that have been accessed in the last $2 days => [Total: $count3]"
    $command3
    echo " "

    command4="find ${dirname}/* -maxdepth 0 -type p,s"
    count4=$( $command4 |wc -l)
    ((count[3]+=$count4))
    echo " "
    echo "4. Find all files in directory of type pipe or socket => [Total: $count4]"
    echo " "

    command5="find ${dirname}/* -maxdepth 0 -empty -type f"
    count5=$( $command5 |wc -l)
    ((count[4]+=$count5))
    echo " "
    echo "5. Find all empty files in directory => [Total: $count5]"
    $command5
    echo " "

    echo "------------"
    echo " "

  done

  echo " "
  echo "Goodbye :)"
  echo " "
  echo "Statistics :"
  for i in "${!count[@]}"; do 
    echo "$(($i+1)). Total=${count[$i]}"
  done

fi

